openapi: 3.0.0
info:
  title: ITSM-ITOM AI Assistant API
  version: 1.0.0
paths:
  /incidents:
    post:
      summary: Create a new incident
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                affected_service:
                  type: string
              required:
                - title
                - description
                - affected_service
      responses:
        '200':
          description: Incident created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  affected_service:
                    type: string
                  ai_severity:
                    type: string
                  ai_category:
                    type: string
                  created_at:
                    type: string
                    format: date-time
